name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: './src'
          extensions: 'c,h,cpp,hpp'
          clangFormatVersion: 17